#As a side note, locations for FFA arenas are not stored as X,Y,Z float or int values. They are stored using the Location object within Bukkit - if you were curious... ;p
#This is why the storing of locations for arenas might look a bit messy.

Kits:
    Archer:
        Price: 0
        DisplayItem: 262
        DisplayName: Archer
    MCSG:
        Price: 0
        DisplayItem: 262
        DisplayName: MCSG
