name: FFA
author: NullChips
version: 1.0
main: me.nullchips.ffa.FFA

commands:
    createffaarena:
        description: Creates an FFA arena.
    ffa:
        description: Join an FFA arena.
    kit:
        description: Get a kit.
    createkit:
        description: Creates a kit.

permissions:
    ffa.joinarena:
        description: Join an FFA arena.
        default: true
    ffa.createarena:
        description: Create an FFA arena.
        default: op
    ffa.createkit:
        description: Create a kit.
        default: op